# Linter Options
options:
  merge-default-rules: true
  formatter: html
  output-file: 'target/sass-lint.html'
  max-warnings: 5
# File Options
#files:
#  include: 'src/main/sass/**/*.scss'
#  ignore:
#    - 'src/main/sass/lib/**/*'
rules:
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: ^[a-z]+[_|\-]?[_\-a-z]* # to be revisited later
  indentation:
    - 2
    -
      size: 2
  nesting-depth:
    - 1
    - max-depth: 3

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 0
  final-newline: 2
  ## these next ones may be reviewed, they are here to match the old scss-lint rules.
#  force-pseudo-nesting: 0
#  force-attribute-nesting: 0
#  force-element-nesting: 0
