scss_files: 'src/main/sass/*.scss'

exclude: 'src/main/sass/libs/**'

linters:
# inherit defaults except:

  Comment:
    enabled: true
    allowed: '^\/\* [a-zA-Z0-9\.\-_]+\.scss \*\/$' # allow file name in head comment.

  DisableLinterReason:
    enabled: true

  ElsePlacement:
    enabled: true
    # default same_line which does not align with our eslint rules and is slightly less readable.
    style: new_line

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: tab # default space
    width: 1 # default 2 (spaces).

  LeadingZero:
    enabled: true
    # including the leading ZERO makes numbers much more readable for humans who have studied mathematics beyond that of
    # a 6 year old. If this is not you then don't play with our Sass!
    style: include_zero

  # Next two (NestingDepth and SelectorDepth) are large due to complex rules. Each has local overrides for some deep
  # selectors which are needed in a complex framework. These are both under review
  NestingDepth:
    enabled: true
    max_depth: 4 # default 3

  # Allow element qualifiers with attribute selectors. We use a lot of attribute selectors and using an element
  # qualifier on a pure attribute selector improves CSS performance.
  QualifyingElement:
    enabled: true #default true
    allow_element_with_attribute: true # default false

  SelectorDepth:
    enabled: true
    max_depth: 4 # default 3

  SelectorFormat:
    enabled: false # selectors include XML element and attribute values in camelCase. We may review this.

  PseudoElement:
      enabled: false
