<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.github.bordertech.wcomponents</groupId>
		<artifactId>wcomponents-parent</artifactId>
		<version>1.5.40-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<name>wcomponents-theme</name>
	<artifactId>wcomponents-theme</artifactId>
	<description>Core client-side WComponents</description>
	<packaging>jar</packaging>

	<properties>
		<theme.skip.antrun>false</theme.skip.antrun>
		<sonar.sources>src/main</sonar.sources>
		<node.download.root>http://nodejs.org/dist/</node.download.root>
		<npm.download.root>http://registry.npmjs.org/npm/-/</npm.download.root>
		<yarn.download.root>https://github.com/yarnpkg/yarn/releases/download/</yarn.download.root>
		<npm.version>10.9.3</npm.version>
		<yarn.version>2.4.3</yarn.version>
		<dependency-check.skip>true</dependency-check.skip>
		<spotbugs.skip>true</spotbugs.skip>
		<nodeAuditSkipDevDependencies>true</nodeAuditSkipDevDependencies>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>${version.org.apache.maven.plugins.maven-clean-plugin}</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>${project.basedir}</directory>
							<includes>
								<include>package-lock.json</include>
							</includes>
						</fileset>
						<fileset>
							<directory>${project.basedir}${file.separator}node_modules</directory>
						</fileset>
						<fileset>
							<directory>${project.basedir}${file.separator}node</directory>
						</fileset>
					</filesets>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.honton.chas</groupId>
				<artifactId>readfiles-maven-plugin</artifactId>
				<version>${version.org.honton.chas.readfiles-maven-plugin}</version>
				<executions>
					<execution>
						<phase>initialize</phase>
						<configuration>
							<files>
								<file>${project.basedir}${file.separator}.nvmrc</file>
							</files>
						</configuration>
						<goals>
							<goal>readfiles</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>${version.org.apache.maven.plugins.maven-assembly-plugin}</version>
				<configuration>
					<ignoreMissingDescriptor>true</ignoreMissingDescriptor>
					<descriptors>
						<descriptor>sources.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>${version.com.github.eirslett.frontend-maven-plugin}</version>
				<configuration>
					<workingDirectory>${project.basedir}</workingDirectory>
					<npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
				</configuration>
				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<phase>generate-resources</phase>
						<configuration>
							<nodeDownloadRoot>${node.download.root}</nodeDownloadRoot>
							<nodeVersion>v${.nvmrc}</nodeVersion>
							<npmDownloadRoot>${npm.download.root}</npmDownloadRoot>
							<npmVersion>${npm.version}</npmVersion>
							<skip>${theme.skip.antrun}</skip>
						</configuration>
					</execution>

					<execution>
						<id>npm-install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<skip>${theme.skip.antrun}</skip>
						</configuration>
					</execution>

					<execution>
						<id>npm-version</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<skip>${theme.skip.antrun}</skip>
							<!--<arguments>version - -no-git-tag-version - -new-version ${project.version}</arguments>-->
							<arguments>version ${project.version} --allow-same-version</arguments>
						</configuration>
					</execution>

					<execution>
						<id>run-build</id>
						<phase>compile</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<skip>${theme.skip.antrun}</skip>
							<arguments>run build</arguments>
						</configuration>
					</execution>

					<execution>
						<id>run-test</id>
						<phase>test</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<skip>${theme.skip.antrun}</skip>
							<arguments>run test:coverage</arguments>
						</configuration>
					</execution>

					<!--
					<execution>
						<!- - Prune the node_modules folder leaving only runtime deps - ->
						<id>prune-production</id>
						<phase>package</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<skip>${theme.skip.antrun}</skip>
							<arguments>install - -production - -no-optional</arguments>
						</configuration>
					</execution>
					-->
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
