dist: focal

env:
  global:
    - MOZ_HEADLESS=1

cache:
  directories:
  - $HOME/.m2

addons:
  firefox: latest
  sonarcloud:
    organization: "bordertech-github"
    token: $SONAR_TOKEN

before_install:
- echo "MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=128m'" > ~/.mavenrc
- mvn clean
## Codacy coverage reporter download
- wget https://github.com/codacy/codacy-coverage-reporter/releases/download/11.9.2/codacy-coverage-reporter-assembly-11.9.2.jar

language: java
jdk:
 - oraclejdk11

## Travis installs the project with the following maven command:- "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install:
 - mvn --settings ci-settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DskipOptionalQA=true -Dpmd.verbose=false

script:
 - ./travis.sh

## Send Coverage to Codacy
after_success:
  - java -jar codacy-coverage-reporter-assembly-11.9.2.jar report -l Java -r wcomponents-core/target/site/jacoco/jacoco.xml
