import uid from "wc/dom/uid.mjs";
import unique from "wc/array/unique.mjs";

describe("wc/dom/uid", function() {
	const ids = [], len = 100;

	beforeAll(() => {
		let i = 0;
		while (i++ < len) {
			ids[ids.length] = uid();
		}
	});

	it("testPrecondition", function() {
		expect(ids.length).withContext("Test case not built correctly").toBe(len);
	});

	it("testUniqueness", function() {
		let uniqueIds = unique(ids);
		expect(uniqueIds.length).withContext("Duplicate ids were generated by uid").toBe(len);
	});

	it("testSortable", function() {
		for (let i= 1; i < ids.length; i++) {
			expect(ids[i - 1]).withContext("ids are not sortable").toBeLessThan(ids[i]);
		}
	});
});
